version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command:
            pip install --user -r backend/requirements.txt
      - run:
          name: Running Djnago tests
          command:
            python3 backend/manage.py test
workflows:
  build_test:
    jobs:
      - run_test
