version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command:
            pip install --user -r backend/requirements.txt
      - run:
          name: Running Django tests
          command:
            python3 backend/manage.py test
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
workflows:
  build_test:
    jobs:
      - run_test
