// global types

export const SET_ERROR = "SET_ERROR"
export const SET_SUCCESS = "SET_SUCCESS"
export const CLEAR_ERROR = "CLEAR_ERROR"
export const CLEAR_SUCCESS = "CLEAR_SUCCESS"
export const DONE_LOADING = "DONE_LOADING"
export const BUSY_LOADING = "BUSY_LOADING"

// accounts types

export const AUTH_LOGOUT = "AUTH_LOGOUT"
export const AUTH_LOGIN = "AUTH_LOGIN"
export const AUTH_REGISTER = "AUTH_REGISTER"
export const AUTH_KILL_SESSION = "AUTH_KILL_SESSION"
export const AUTH_UPDATE_USER = "AUTH_UPDATE_USER"
export const GET_USER = "GET_USER"
export const VERIFY_PAYMENT = "VERIFY_PAYMENT"

export const AUTH_FAILED = "AUTH_FAILED"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const SET_USER = "SET_USER"
export const VERIFICATION_FAILED = "VERIFICATION_FAILED"
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS"

// store types

export const CREATE_STORE = "CREATE_STORE"
export const GET_STORE = "GET_STORE"
export const GET_STORE_LIST = "GET_STORE_LIST"
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST"
export const GET_STORE_PRODUCTS = "GET_STORE_PRODUCTS"

export const SET_STORE = "SET_STORE"
export const SET_STORE_LIST = "SET_STORE_LIST"
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST"
export const SET_STORE_PRODUCTS = "SET_STORE_PRODUCTS"

// cart types

export const GET_CART = "GET_CART"
export const UPDATE_CART = "UPDATE_CART"
export const BUY_NOW = "BUY_NOW"
export const CHECKOUT_CART = "CHECKOUT_CART"

export const SET_CART = "SET_CART"
export const SET_CART_PURCHASE_SUCCESS = "SET_CART_PURCHASE_SUCCESS"

// product types

export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAILED = "CREATE_PRODUCT_FAILED"

// admin types

export const GET_ADMIN_USERS_LIST = "GET_ADMIN_USERS_LIST"
export const GET_ADMIN_RIDERS_LIST = "GET_ADMIN_RIDERS_LIST"

export const SET_ADMIN_USERS_LIST = "SET_ADMIN_USERS_LIST"
export const SET_ADMIN_RIDERS_LIST = "SET_ADMIN_RIDERS_LIST"

// order types

export const GET_ORDERS = "GET_ORDERS"
export const GET_ADMIN_ORDERS = "GET_ADMIN_ORDERS"

export const SET_ORDERS = "SET_ORDERS"
export const SET_ADMIN_ORDERS = "SET_ADMIN_ORDERS"

// wallet types

export const FUND_WALLET = "FUND_WALLET"
export const GET_WALLET_FUND_HISTORY = "GET_WALLET_FUND_HISTORY"

export const SET_FUND_WALLET_SUCCESS = "SET_FUND_WALLET_SUCCESS"
export const SET_FUND_WALLET_FAILED = "SET_FUND_WALLET_FAILED"
export const SET_FUND_WALLET_HISTORY = "SET_FUND_WALLET_HISTORY"
